=== binaryhardware/fpga-chips/chips/xml/xilinx/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="product">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="chipset">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="chip" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="res_logic">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="slices" type="xs:string" />
                                                    <xs:element name="cells" type="xs:string" />
                                                    <xs:element name="clbff" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_mem">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dist_mem">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="Kb" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="bram">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="36Kb" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="total_ram">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="Kb" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_clk">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cmt">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" fixed="1mmcm+1pll" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_io">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="io" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="io_diff_pair" />
                                                                                <xs:enumeration value="io_signle" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_integrated">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dsp">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" >
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="DSP48A1" />
                                                                                <xs:enumeration value="DSP48E1" />
                                                                                <xs:enumeration value="DSP48E2" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>   
                                                                    </xs:attribute>
                                                             </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="pcie" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="Gen2" />
                                                                                <xs:enumeration value="Gen3" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="ams">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" fixed="XADC" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="conf_hmac">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" fixed="AES/HMAC" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="transiver" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="gtp" />
                                                                                <xs:enumeration value="gth" />
                                                                                <xs:enumeration value="gtx" />
                                                                                <xs:enumeration value="gtz" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                    <xs:attribute name="rate" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="6.6_Gbps" />
                                                                                <xs:enumeration value="12.5_Gbps" />
                                                                                <xs:enumeration value="13.1_Gbps" />
                                                                                <xs:enumeration value="28.5_Gbps" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="speed_grade">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="speed" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">

                                                                    <xs:attribute name="temp" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="C" />
                                                                                <xs:enumeration value="I" />
                                                                                <xs:enumeration value="E" />
                                                                                <xs:enumeration value="Q" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="commercial" />
                                                                                <xs:enumeration value="extended" />
                                                                                <xs:enumeration value="industrial" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="pnum" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="familiy" use="required" />
                        <xs:attribute name="type" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="vendor" use="required" />
            <xs:attribute name="series" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== binaryhardware/fpga-chips/chips/xml/xilinx/kintex7.xml
<?xml version="1.0" encoding="UTF-8"?>

<product 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="products.xsd" 
    vendor="xilinx.com" 
    series='7series'>
    <chipset familiy='kintex7' type='programmable_logic'>
        <chip pnum='XC7K70T'>
            <res_logic>
                <slices>10250</slices>
                <cells >65600</cells>
                <clbff >82000</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >838</dist_mem>
                <bram unit='36Kb'   >135</bram>
                <total_ram unit='Kb'>4860</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>6</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>300</io>
                <io type='io_diff_pair'>144</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>240</dsp>
                <pcie type='Gen2'>1</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>8</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed temp='commercial'>{-1,-2}</speed>
                <speed temp='extended'>{-2L,-3}</speed>
                <speed temp='industrial'>{-1,-2}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7K160T'>
            <res_logic>
                <slices>25350</slices>
                <cells >162240</cells>
                <clbff >202800</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >2188</dist_mem>
                <bram unit='36Kb'   >325</bram>
                <total_ram unit='Kb'>11700</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>8</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>400</io>
                <io type='io_diff_pair'>192</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>600</dsp>
                <pcie type='Gen2'>1</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>8</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed temp='commercial'>{-1,-2}</speed>
                <speed temp='extended'>{-2L,-3}</speed>
                <speed temp='industrial'>{-1,-2,-2L}</speed>
            </speed_grade>
        </chip>
   
        <chip pnum='XC7K325T'>
            <res_logic>
                <slices>50950</slices>
                <cells >326080</cells>
                <clbff >407600</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >4000</dist_mem>
                <bram unit='36Kb'   >445</bram>
                <total_ram unit='Kb'>16020</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>10</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>500</io>
                <io type='io_diff_pair'>240</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>840</dsp>
                <pcie type='Gen2'>1</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>16</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed temp='commercial'>{-1,-2}</speed>
                <speed temp='extended'>{-2L,-3}</speed>
                <speed temp='industrial'>{-1,-2,-2L}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7K355T'>
            <res_logic>
                <slices>55650</slices>
                <cells >356160</cells>
                <clbff >445200</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >5088</dist_mem>
                <bram unit='36Kb'   >715</bram>
                <total_ram unit='Kb'>25740</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>6</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>300</io>
                <io type='io_diff_pair'>144</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>1440</dsp>
                <pcie type='Gen2'>1</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>24</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed temp='commercial'>{-1,-2}</speed>
                <speed temp='extended'>{-2L,-3}</speed>
                <speed temp='industrial'>{-1,-2,-2L}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7K410T'>
            <res_logic>
                <slices>63550</slices>
                <cells >406720</cells>
                <clbff >508400</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >5663</dist_mem>
                <bram unit='36Kb'   >795</bram>
                <total_ram unit='Kb'>28620</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>10</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>500</io>
                <io type='io_diff_pair'>240</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>1540</dsp>
                <pcie type='Gen2'>1</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>16</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed temp='commercial'>{-1,-2}</speed>
                <speed temp='extended'>{-2L,-3}</speed>
                <speed temp='industrial'>{-1,-2,-2L}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7K420T'>
            <res_logic>
                <slices>65150</slices>
                <cells >416960</cells>
                <clbff >521200</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >5938</dist_mem>
                <bram unit='36Kb'   >835</bram>
                <total_ram unit='Kb'>30060</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>8</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>400</io>
                <io type='io_diff_pair'>192</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>1680</dsp>
                <pcie type='Gen2'>1</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>32</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed temp='commercial'>{-1,-2}</speed>
                <speed temp='extended'>{-2L,-3}</speed>
                <speed temp='industrial'>{-1,-2,-2L}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7K480T'>
            <res_logic>
                <slices>74650</slices>
                <cells >477760</cells>
                <clbff >597200</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >6788</dist_mem>
                <bram unit='36Kb'   >955</bram>
                <total_ram unit='Kb'>34380</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>8</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>400</io>
                <io type='io_diff_pair'>192</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>1920</dsp>
                <pcie type='Gen2'>1</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>32</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed temp='commercial'>{-1,-2}</speed>
                <speed temp='extended'>{-2L,-3}</speed>
                <speed temp='industrial'>{-1,-2,-2L}</speed>
            </speed_grade>
        </chip>
    </chipset>
</product>
