=== binaryhardware/fpga-chips/chips/xml/xilinx/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="product">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="chipset">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="chip" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="res_logic">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="slices" type="xs:string" />
                                                    <xs:element name="cells" type="xs:string" />
                                                    <xs:element name="clbff" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_mem">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dist_mem">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="Kb" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="bram">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="36Kb" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="total_ram">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="unit" use="required" fixed="Kb" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_clk">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="cmt">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" fixed="1mmcm+1pll" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_io">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="io" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="io_diff_pair" />
                                                                                <xs:enumeration value="io_signle" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="res_integrated">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dsp">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" >
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="DSP48A1" />
                                                                                <xs:enumeration value="DSP48E1" />
                                                                                <xs:enumeration value="DSP48E2" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>   
                                                                    </xs:attribute>
                                                             </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="pcie" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="Gen2" />
                                                                                <xs:enumeration value="Gen3" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="ams">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" fixed="XADC" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="conf_hmac">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required" fixed="AES/HMAC" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="transiver" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="gtp" />
                                                                                <xs:enumeration value="gth" />
                                                                                <xs:enumeration value="gtx" />
                                                                                <xs:enumeration value="gtz" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                    <xs:attribute name="rate" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="6.6_Gbps" />
                                                                                <xs:enumeration value="12.5_Gbps" />
                                                                                <xs:enumeration value="13.1_Gbps" />
                                                                                <xs:enumeration value="28.5_Gbps" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="speed_grade">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="speed" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">

                                                                    <xs:attribute name="temp" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="C" />
                                                                                <xs:enumeration value="I" />
                                                                                <xs:enumeration value="E" />
                                                                                <xs:enumeration value="Q" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                    <xs:attribute name="type" use="required">
                                                                        <xs:simpleType>
                                                                            <xs:restriction base="xs:string">
                                                                                <xs:enumeration value="commercial" />
                                                                                <xs:enumeration value="extended" />
                                                                                <xs:enumeration value="industrial" />
                                                                            </xs:restriction>
                                                                        </xs:simpleType>
                                                                    </xs:attribute>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="pnum" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="familiy" use="required" />
                        <xs:attribute name="type" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="vendor" use="required" />
            <xs:attribute name="series" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== binaryhardware/fpga-chips/chips/xml/xilinx/spartan7.xml
<?xml version="1.0" encoding="UTF-8"?>

<product 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="products.xsd" 
    vendor="xilinx.com" 
    series='7series'>
    <chipset familiy='spartan7' type='programmable_logic'>

        <chip pnum='XC7S6'>
            <res_logic>
                <slices>6000</slices>
                <cells >938</cells>
                <clbff >7500</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >70</dist_mem>
                <bram unit='36Kb'   >5</bram>
                <total_ram unit='Kb'>180</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>2</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>100</io>
                <io type='io_diff_pair'>48</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>10</dsp>
                <pcie type='Gen2'>0</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>0</ams>
                <conf_hmac type='AES/HMAC'>0</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>0</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed type='commercial' temp='C'>{-1,-2}</speed>
                <speed type='industrial' temp='I'>{-1,-2,-1L}</speed>
                <speed type='extended' temp='Q'>{-1}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7S15'>
            <res_logic>
                <slices>12800</slices>
                <cells >2000</cells>
                <clbff >16000</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >150</dist_mem>
                <bram unit='36Kb'   >10</bram>
                <total_ram unit='Kb'>360</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>2</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>100</io>
                <io type='io_diff_pair'>48</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>20</dsp>
                <pcie type='Gen2'>0</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>0</ams>
                <conf_hmac type='AES/HMAC'>0</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>0</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>

            <speed_grade>
                <speed type='commercial' temp='C'>{-1,-2}</speed>
                <speed type='industrial' temp='I'>{-1,-2,-1L}</speed>
                <speed type='extended' temp='Q'>{-1}</speed>
            </speed_grade>
        </chip>
       
        <chip pnum='XC7S25'>
            <res_logic>
                <slices>23360</slices>
                <cells >3650</cells>
                <clbff >29200</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >313</dist_mem>
                <bram unit='36Kb'   >45</bram>
                <total_ram unit='Kb'>1620</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>3</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>150</io>
                <io type='io_diff_pair'>72</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>80</dsp>
                <pcie type='Gen2'>0</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>0</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed type='commercial' temp='C'>{-1,-2}</speed>
                <speed type='industrial' temp='I'>{-1,-2,-1L}</speed>
                <speed type='extended' temp='Q'>{-1}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7S50'>
            <res_logic>
                <slices>52160</slices>
                <cells >8150</cells>
                <clbff >65200</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >600</dist_mem>
                <bram unit='36Kb'   >75</bram>
                <total_ram unit='Kb'>2700</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>5</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>250</io>
                <io type='io_diff_pair'>120</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>120</dsp>
                <pcie type='Gen2'>0</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>0</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed type='commercial' temp='C'>{-1,-2}</speed>
                <speed type='industrial' temp='I'>{-1,-2,-1L}</speed>
                <speed type='extended' temp='Q'>{-1}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7S75'>
            <res_logic>
                <slices>76800</slices>
                <cells >12000</cells>
                <clbff >96000</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >832</dist_mem>
                <bram unit='36Kb'   >90</bram>
                <total_ram unit='Kb'>3240</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>8</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>400</io>
                <io type='io_diff_pair'>192</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>140</dsp>
                <pcie type='Gen2'>0</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>0</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed type='commercial' temp='C'>{-1,-2}</speed>
                <speed type='industrial' temp='I'>{-1,-2,-1L}</speed>
                <speed type='extended' temp='Q'>{-1}</speed>
            </speed_grade>
        </chip>

        <chip pnum='XC7S100'>
            <res_logic>
                <slices>102400</slices>
                <cells >16000</cells>
                <clbff >128000</clbff>
            </res_logic>
            <res_mem>
                <dist_mem unit='Kb' >1100</dist_mem>
                <bram unit='36Kb'   >120</bram>
                <total_ram unit='Kb'>4320</total_ram>
            </res_mem>
            <res_clk>
                <cmt type='1mmcm+1pll'>8</cmt>
            </res_clk>
            <res_io>
                <io type='io_signle'>400</io>
                <io type='io_diff_pair'>192</io>
            </res_io>
            <res_integrated>
                <dsp type='DSP48E1'>160</dsp>
                <pcie type='Gen2'>0</pcie>
                <pcie type='Gen3'>0</pcie>
                <ams type='XADC'>1</ams>
                <conf_hmac type='AES/HMAC'>1</conf_hmac>
                <transiver type='gtx' rate='12.5_Gbps'>0</transiver>
                <transiver type='gth' rate='13.1_Gbps'>0</transiver>
                <transiver type='gtz' rate='28.5_Gbps'>0</transiver>
            </res_integrated>
            <speed_grade>
                <speed type='commercial' temp='C'>{-1,-2}</speed>
                <speed type='industrial' temp='I'>{-1,-2,-1L}</speed>
                <speed type='extended' temp='Q'>{-1}</speed>
            </speed_grade>
        </chip>
        
    </chipset>
</product>
